export const mapPoints = [
  { name: 'Pokój Dyrektora Call Center', id: 5 },
  { name: 'Pokój Kierowników Call Center', id: 4 },
  { name: 'Biuro Działu Prawnego', id: 3 },
  { name: 'Biuro Zarządu', id: 2 },
  { name: 'Recepcja', id: 1 },
  { name: 'Biuro Wspólne', id: 44 },
  { name: 'Biuro Księgowości', id: 43 },
  { name: 'Biuro Service Desk', id: 14 },
  { name: 'Biuro Działu Kard i Płac 1', id: 13 },
  { name: 'Biuro Działu Kard i Płac 2', id: 12 },
  { name: 'Biuro Działu Kard i Płac 3', id: 11 },
  { name: 'Biuro Testerów', id: 15 },
  { name: 'Gabinet Prezesa', id: 42 },
  { name: 'Gabinet CFO', id: 41 },
  { name: 'Gabinet Vice Prezesa', id: 40 },
  { name: 'Coffe Point', id: 38 },
  { name: 'Strefa Wspólna 1', id: 35 },
  { name: 'Strefa Wspólna 2', id: 29 },
  { name: 'Strefa Wspólna 3', id: 9 },
  { name: 'Sala Konferencyjna 1', id: 37 },
  { name: 'Sala Konferencyjna 2', id: 36 },
  { name: 'Sala Konferencyjna 3', id: 33 },
  { name: 'Sala Konferencyjna 4', id: 28 },
  { name: 'Sala Konferencyjna 5', id: 24 },
  { name: 'Sala Konferencyjna 6', id: 23 },
  { name: 'Sala Konferencyjna 7', id: 20 },
  { name: 'Sala Konferencyjna 8', id: 19 },
  { name: 'Sala Szkoleniowa', id: 30 },
  { name: 'Open Space 1', id: 34 },
  { name: 'Open Space Call Center 1', id: 6 },
  { name: 'Open Space Call Center 2', id: 10 },
  { name: 'Open Space Ecommerce & Engineering', id: 21 },
  { name: 'Open Space Core Systems', id: 16 },
  { name: 'Gabinet Dyrektora Marketingu', id: 39 },
  { name: 'Gabinet HRBP', id: 18 },
  { name: 'Gabinet Dyrektora IT', id: 17 },
  { name: 'Garderoba 1', id: 31 },
  { name: 'Garderoba 2', id: 7 },
  { name: 'Garderoba 3', id: 25 },
  { name: 'Magazyn 1', id: 32 },
  { name: 'Magazyn 2', id: 22 },
  { name: 'Serwerownia', id: 27 },
  { name: 'Pokój Matki i Dziecka', id: 26 },
  { name: 'Kuchnia', id: 8 },
]
