import { Tools } from '@/content/Tools'
import Unleash from '../content/unleash.mdx'
import Vitals from '../content/vitals.mdx'
import { Devs } from '@/content/Devs'

export const tabsGroup = {
  AUTOMATIC_TESTER: [],
  FRONTEND: [
    {
      value: 'apps',
      label: 'Devs 4 Devs',
      content: <Devs />,
      id: 1,
    },
    {
      value: 'unleash',
      label: 'Unleash',
      content: <Unleash />,
      id: 2,
    },
    {
      value: 'vitals',
      label: 'Web Vitals',
      content: <Vitals />,
      id: 3,
    },
    {
      value: 'config',
      label: 'Narzędzia',
      content: <Tools />,
      id: 4,
    },
  ],
}

export const groupsData = [
  {
    groupName: 'Front',
    avatar: 'Frontend',
    bgColor: 'bg-zinc-600',
    groupId: 0,
    participants: [
      {
        id: 1,
        name: 'Uczestnik1 Front',
        email: 'uczestnik1@front.com',
        avatar: 'UF',
        bgColor: 'bg-red-500',
        contact: 123123123,
        vpn: 'Tak',
        umowa: '2024-11-05',
        RODO: 'Nie',
        ZPC: 'Tak',
      },
      {
        id: 2,
        name: 'Uczestnik2 Front',
        email: 'uczestnik2@front.com',
        avatar: 'UF',
        bgColor: 'bg-lime-500',
        contact: 123123123,
        vpn: 'Tak',
        umowa: '2024-11-05',
        RODO: 'Nie',
        ZPC: 'Tak',
      },
      {
        id: 3,
        name: 'Uczestnik3 Front',
        email: 'uczestnik3@front.com',
        avatar: 'UF',
        bgColor: 'bg-blue-500',
        contact: 123123123,
        vpn: 'Tak',
        umowa: '2024-11-05',
        RODO: 'Nie',
        ZPC: 'Tak',
      },
      {
        id: 4,
        name: 'Uczestnik4 Front',
        email: 'uczestnik4@front.com',
        avatar: 'UF',
        bgColor: 'bg-cyan-500',
        contact: 123123123,
        vpn: 'Tak',
        umowa: '2024-11-05',
        RODO: 'Nie',
        ZPC: 'Tak',
      },
    ],
  },
  {
    groupName: 'Call Center',
    avatar: 'Call Center',
    bgColor: 'bg-cyan-600',
    groupId: 1,
    participants: [
      {
        id: 1,
        name: 'Uczestnik1 Call Center',
        email: 'uczestnik1@callcenter.com',
        avatar: 'UCC',
        bgColor: 'bg-green-500',
        contact: 123123123,
        vpn: 'Tak',
        umowa: '2024-11-05',
        RODO: 'Nie',
        ZPC: 'Tak',
      },
      {
        id: 2,
        name: 'Uczestnik2 Call Center',
        email: 'uczestnik2@callcenter.com',
        avatar: 'UCC',
        bgColor: 'bg-zinc-500',
        contact: 123123123,
        vpn: 'Tak',
        umowa: '2024-11-05',
        RODO: 'Nie',
        ZPC: 'Tak',
      },
      {
        id: 3,
        name: 'Uczestnik3 Call Center',
        email: 'uczestnik3@callcenter.com',
        avatar: 'UCC',
        bgColor: 'bg-red-500',
        contact: 123123123,
        vpn: 'Tak',
        umowa: '2024-11-05',
        RODO: 'Nie',
        ZPC: 'Tak',
      },
    ],
  },
  {
    groupName: 'Back Office',
    avatar: 'Back Office',
    bgColor: 'bg-lime-500',
    groupId: 2,
    participants: [
      {
        id: 1,
        name: 'Uczestnik1 Back Office',
        email: 'uczestnik1@backoffice.com',
        avatar: 'UBO',
        bgColor: 'bg-blue-500',
        contact: 123123123,
        vpn: 'Tak',
        umowa: '2024-11-05',
        RODO: 'Nie',
        ZPC: 'Tak',
      },
      {
        id: 2,
        name: 'Uczestnik2 Back Office',
        email: 'uczestnik2@backoffice.com',
        avatar: 'UBO',
        bgColor: 'bg-zinc-500',
        contact: 123123123,
        vpn: 'Tak',
        umowa: '2024-11-05',
        RODO: 'Nie',
        ZPC: 'Tak',
      },
      {
        id: 3,
        name: 'Uczestnik3 Back Office',
        email: 'uczestnik3@backoffice.com',
        avatar: 'UBO',
        bgColor: 'bg-red-500',
        contact: 123123123,
        vpn: 'Tak',
        umowa: '2024-11-05',
        RODO: 'Nie',
        ZPC: 'Tak',
      },
      {
        id: 4,
        name: 'Uczestnik4 Back Office',
        email: 'uczestnik4@backoffice.com',
        avatar: 'UBO',
        bgColor: 'bg-lime-500',
        contact: 123123123,
        vpn: 'Tak',
        umowa: '2024-11-05',
        RODO: 'Nie',
        ZPC: 'Tak',
      },
      {
        id: 5,
        name: 'Uczestnik5 Back Office',
        email: 'uczestnik5@backoffice.com',
        avatar: 'UBO',
        bgColor: 'bg-cyan-500',
        contact: 123123123,
        vpn: 'Tak',
        umowa: '2024-11-05',
        RODO: 'Nie',
        ZPC: 'Tak',
      },
    ],
  },
]
