import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { getNavigationData, Menu } from '@/lib/api/getNavigationData'
import { userGroupName } from '@/constants/constants'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {

  const menu = await getNavigationData(userGroupName.HR)
  console.log(menu)

  return (
    <html lang='en'>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
